# Welcome 2 my library code ..written in teen language hehe


from datetime import datetime, timedelta
from library_books import library_books   

# ---------------------- RANDOM HELPER THINGS ----------------------

def find_book(books, bid):
    
        for b in books:
                if b.id == bid:
                            return b
                                return None


                                # ---------------------- BOOK CLASS TIME ---------------------------

                                class Book:
                                   
                                       def __init__(self, id, title, author, genre, available=True, due_date=None, checkouts=0):
                                               self.id = id
                                                       self.title = title
                                                               self.author = author
                                                                       self.genre = genre
                                                                               self.available = available
                                                                                       self.due_date = due_date
                                                                                               self.checkouts = checkouts

                                                                                                   def checkout(self):
                                                                                                          
                                                                                                                  if not self.available:
                                                                                                                              print("nah this book is already taken bro")
                                                                                                                                          return

                                                                                                                                                  self.available = False
                                                                                                                                                          due = datetime.today() + timedelta(days=14)
                                                                                                                                                                  self.due_date = due.strftime("%Y-%m-%d")
                                                                                                                                                                          self.checkouts += 1
                                                                                                                                                                                  print(f"ok u got '{self.title}', bring it back pls pls pls by {self.due_date}")

                                                                                                                                                                                      def return_book(self):
                                                                                                                                                                                              if self.available:
                                                                                                                                                                                                          print("u tryna return something u don't have...")
                                                                                                                                                                                                                      return
                                                                                                                                                                                                                              self.available = True
                                                                                                                                                                                                                                      self.due_date = None
                                                                                                                                                                                                                                              print("yay thx 4 returning ur book")


                                                                                                                                                                                                                                              # ---------------------- CONVERT DICTS → OBJECTS -------------------

                                                                                                                                                                                                                                              def load_books():
                                                                                                                                                                                                                                                  # transforms the starter dicts into actual objects bc oop is cool
                                                                                                                                                                                                                                                      new = []
                                                                                                                                                                                                                                                          for b in library_books:
                                                                                                                                                                                                                                                                  bb = Book(
                                                                                                                                                                                                                                                                              b["id"],
                                                                                                                                                                                                                                                                                          b["title"],
                                                                                                                                                                                                                                                                                                      b["author"],
                                                                                                                                                                                                                                                                                                                  b["genre"],
                                                                                                                                                                                                                                                                                                                              b["available"],
                                                                                                                                                                                                                                                                                                                                          b["due_date"],
                                                                                                                                                                                                                                                                                                                                                      b["checkouts"]
                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                      new.append(bb)
                                                                                                                                                                                                                                                                                                                                                                          return new


                                                                                                                                                                                                                                                                                                                                                                          # ---------------------- LVL 1: VIEW AVAILABLE --------------------

                                                                                                                                                                                                                                                                                                                                                                          def show_available(books):
                                                                                                                                                                                                                                                                                                                                                                              print("\n=== BOOKS U CAN ACTUALLY TAKE ===")
                                                                                                                                                                                                                                                                                                                                                                                  for b in books:
                                                                                                                                                                                                                                                                                                                                                                                          if b.available:
                                                                                                                                                                                                                                                                                                                                                                                                      print(f"{b.id} | {b.title} by {b.author}")


                                                                                                                                                                                                                                                                                                                                                                                                      # ---------------------- LVL 2: SEARCH -----------------------------

                                                                                                                                                                                                                                                                                                                                                                                                      def search_stuff(books):
                                                                                                                                                                                                                                                                                                                                                                                                          w = input("author or genre? idk u choose: ").lower().strip()
                                                                                                                                                                                                                                                                                                                                                                                                              print("\n=== RESULTS OR WHATEVER ===")
                                                                                                                                                                                                                                                                                                                                                                                                                  for b in books:
                                                                                                                                                                                                                                                                                                                                                                                                                          if b.author.lower() == w or b.genre.lower() == w:
                                                                                                                                                                                                                                                                                                                                                                                                                                      print(f"{b.id} | {b.title} ({b.genre})")


                                                                                                                                                                                                                                                                                                                                                                                                                                      # ---------------------- LVL 3: CHECKOUT ---------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                      def checkout_book(books):
                                                                                                                                                                                                                                                                                                                                                                                                                                          bid = input("enter book id u want: ").strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                              da_book = find_book(books, bid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if da_book is None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                          print("bro that's not even a real id...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                              else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      da_book.checkout()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # ---------------------- LVL 4: RETURNS + OVERDUE ------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      def ret(books):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bid = input("enter book id to return: ").strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              da_book = find_book(books, bid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if da_book:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          da_book.return_book()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print("nope. that aint a book.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      def overdue_list(books):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print("\n=== OMG THESE BOOKS R LATEEEE ===")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              today = datetime.today().date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for b in books:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if not b.available and b.due_date:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      d = datetime.strptime(b.due_date, "%Y-%m-%d").date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if d < today:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print(f"{b.id} | {b.title} | due {b.due_date}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # ---------------------- TOP 3 CHECKOUTS ---------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  def top3(books):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print("\n=== MOST POPULAR BOOKS BC YALL BASIC ===")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          arr = sorted(books, key=lambda x: x.checkouts, reverse=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for b in arr[:3]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print(f"{b.title} (checked out {b.checkouts}x)")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # ---------------------- LVL 5: MENU (chaotic edition) -------------


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      def menu():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          books = load_books()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      -------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              welcome 2 da LIBRARY MENU
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      -------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1. show available books 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2. search (author/genre)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3. checkout sum book
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      4. return ur book pls
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              5. overdue drip check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      6. top 3 most checked out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0. exit bc u hate reading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      """)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              choice = input("pick a number: ").strip()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if choice == "1":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  show_available(books)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          elif choice == "2":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      search_stuff(books)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              elif choice == "3":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          checkout_book(books)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  elif choice == "4":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ret(books)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      elif choice == "5":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overdue_list(books)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          elif choice == "6":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      top3(books)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              elif choice == "0":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print("mk bye nerd ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print("?? bro what kind of choice is that")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # only run menu if u actually run this file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              menu()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              